#!env bash

progname=$(basename $0)

function help(){
    cat <<EOT
Usage:
  gh-release-get [(-h|--help)] [(-d|--install-dir) <dir>] [--url <url>]
Options:
  -h, --help        Displays this information
  -d, --install-dir Install directory (abusolute or relative path) (Default: $HOME/bin)
      --url         GitHub URL (Default: https://github.com)
EOT
    exit 1;
}

for OPT in "$@"
do
    case "$OPT" in
        '-h' | '--help' )
            help
            ;;
        '-d' | '--install-dir' )
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                echo "option requires an argument: $1" 1>&2
                exit 1
            fi
            install_dir="$2"
            shift 2
            ;;
        '--url' )
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                echo "option requires an argument: $1" 1>&2
                exit 1
            fi
            gh_url="$2"
            shift 2
            ;;
        -*)
            echo "illegal option: $1" 1>&2
            exit 1
            ;;
        *)
            if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
                repo=$1
                shift 1
            fi
            ;;
    esac
done

if [ -z $repo ]; then
    echo "reposity name is required" 1>&2
    exit 1
fi

# set default values
if [ -z "$install_dir" ]; then
    install_dir="$HOME/bin"
fi

if [ -z "$gh_url" ]; then
    gh_url='https://github.com'
fi

user=`echo $repo | awk -F/ '{print $1}'`
project=`echo $repo | awk -F/ '{print $2}'`
os=`uname | tr "A-Z" "a-z"`
processor=`uname -p | tr -d 'i'`
pattern="\/${user}\/${project}\/releases\/download\/[^/]+\/[^_]+_${os}_${processor}[^\"]+"
dl_path=`curl -sL "${gh_url}/${user}/${project}/releases" | sed -Ene "1,/$pattern/s/.*($pattern).*/\1/p"`
if [ -z $dl_path ];then
    echo "Can't get download url"
    exit 1
fi

tmpdir=`mktemp -d /tmp/gh-release-get.XXXXXX`
pushd $tmpdir >/dev/null
curl -LO "${gh_url}/$dl_path"
file=`echo $dl_path | sed -Ee 's/.*\/([^/]+)$/\1/'`

case $file in
    *tar.gz)
        gzip -dc $file | tar xvf -
        ;;
    *zip)
        unzip $file
        ;;
    *)
        echo 'unknown extension'
        exit 1
        ;;
esac

dir=`echo $file | sed -Ee 's/^([^.]+).*$/\1/'`
cmd=`echo $file | sed -Ee 's/^([^_]+).*$/\1/'`
popd >/dev/null

mv ${tmpdir}/${dir}/${cmd} $install_dir
echo "Installed to $install_dir"
